# Generated by Django 3.2.2 on 2021-05-08 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_company', models.CharField(max_length=200)),
                ('car_rent', models.FloatField()),
                ('car_kilometers', models.FloatField()),
                ('car_last_rented', models.DateField()),
                ('car_condition', models.CharField(max_length=200)),
                ('car_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=200)),
                ('cus_phone', models.IntegerField(default=0)),
                ('date_rented', models.DateField()),
                ('date_returned', models.DateField()),
                ('cus_status', models.CharField(max_length=200)),
                ('rented_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.car')),
            ],
        ),
    ]
