# Generated by Django 3.2.3 on 2021-05-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_car_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.FloatField()),
                ('carid', models.FloatField()),
                ('rentedDate', models.DateField()),
                ('returnDate', models.DateField()),
            ],
        ),
    ]
