# Generated by Django 3.2.3 on 2021-05-16 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='rentedDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 16, 12, 53, 27, 57661)),
        ),
        migrations.AlterField(
            model_name='logs',
            name='returnDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
