# Generated by Django 3.2.2 on 2021-05-20 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_auto_20210516_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='carid',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='logs',
            name='rentedDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 20, 11, 29, 31, 939849)),
        ),
    ]
