# Generated by Django 3.2.2 on 2021-05-20 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0005_auto_20210520_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='rentedDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 20, 12, 0, 59, 301777)),
        ),
    ]
