# Generated by Django 3.2.2 on 2021-05-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0006_alter_logs_renteddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='rentedDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='returnDate',
            field=models.DateField(null=True),
        ),
    ]
